### ISSUE TITLE
Last line in raw stack not being processed

### ISSUE THREAD

**Issue by NoelAbrahams** [SponsorPay/stack-retrace#11]
Version: **0.1.8**

Given the following raw stack
```
Error: LoadFailed 
at e.terminateLoad (https://foo/og-1.1.7.0.js:13:19711)
at e.loadErrorHandler (https://foo/og-1.1.7.0.js:13:19566) 
at i.callHandler (https://foo/og-1.1.7.0.js:8:8734) 
at HTMLImageElement.<anonymous> (https://foo/og-1.1.7.0.js:8:6720); 
```

I get the following result:

```json
[
   {
      "fileName": "?",
      "lineNumber": 22050,
      "columnNumber": 39,
      "functionName": "e.terminateLoad"
   },
   {
      "fileName": "?",
      "lineNumber": 22040,
      "columnNumber": 25,
      "functionName": "terminateLoad"
   },
   {
      "fileName": "?",
      "lineNumber": 11656,
      "columnNumber": 28,
      "functionName": "call"
   },
   {
      "fileName": "https://foo/og-1.1.7.0.js:8:6720);",
      "functionName": "HTMLImageElement.<anonymous>"
   }
]
```

The last line starting `HTMLImageElement` is not being processed. There is no `lineNumber`, `columnNumber`.

Otherwise the result is fine.

**Comment by NoelAbrahams** [comment]
I should add that in some cases the last line is quite important to figure out the original caller.

**Comment by NoelAbrahams** [comment]
Simpler example:

```
Error: Load failed at HTMLScriptElement.<anonymous> (https://foo/og-1.1.7.0.js:8:11899);
```
